services:
  postgres:
    image: postgres:latest
    container_name: postgres_AIS
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - "${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      bash -c "echo 'Dropping and recreating database...';
      psql -U postgres -c 'DROP DATABASE IF EXISTS ${DATABASE_NAME};';
      psql -U postgres -c 'CREATE DATABASE ${DATABASE_NAME} OWNER ${DATABASE_USERNAME};';
      echo 'Database ready!';
      exec docker-entrypoint.sh postgres"

# docker-compose down -v
# docker-compose up -d
